"""add squid_players table

Revision ID: d490bbcf8b70
Revises: 
Create Date: 2026-09-05 13:17:33.080198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd490bbcf8b70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squid_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squid_players_id'), 'squid_players', ['id'], unique=False)
    op.create_index(op.f('ix_squid_players_name'), 'squid_players', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_squid_players_name'), table_name='squid_players')
    op.drop_index(op.f('ix_squid_players_id'), table_name='squid_players')
    op.drop_table('squid_players')
    # ### end Alembic commands ###
